services:
  xrx-client:
    container_name: xrx-client
    build:
      context: ./nextjs-client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - xrx_network

  xrx-orchestrator:
    container_name: xrx-orchestrator
    build:
      context: ../../orchestrator
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    env_file:
      - .env
    networks:
      - xrx_network

  xrx-reasoning:
    container_name: xrx-reasoning
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8093:8093
    env_file:
      - .env
    networks:
      - xrx_network

  xrx-stt:
    container_name: xrx-stt
    build:
      context: ../../stt
      dockerfile: Dockerfile
    ports:
      - 8091:8091
    env_file:
      - .env
    networks:
      - xrx_network

  xrx-tts:
    container_name: xrx-tts
    build:
      context: ../../tts
      dockerfile: Dockerfile
    ports:
      - 8092:8092
    env_file:
      - .env
    networks:
      - xrx_network

  xrx-guardrails:
    container_name: xrx-guardrails
    build:
      context: ../../guardrails-proxy
      dockerfile: Dockerfile
    ports:
      - 8094:8094
    env_file:
      - .env
    networks:
      - xrx_network

  xrx-redis:
    image: "redis:alpine"
    container_name: xrx-redis
    ports:
      - 6379:6379
    networks:
      - xrx_network

networks:
  xrx_network:
    driver: bridge
